package com.gt.dao.common;

import com.gt.entity.common.BusErpLog;

public interface BusErpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_erp_log
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_erp_log
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    int insert(BusErpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_erp_log
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    int insertSelective(BusErpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_erp_log
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    BusErpLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_erp_log
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    int updateByPrimaryKeySelective(BusErpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_erp_log
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    int updateByPrimaryKey(BusErpLog record);
}