package com.gt.dao.common;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.gt.entity.common.BusUser;

public interface BusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    int insert(BusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    int insertSelective(BusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    BusUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(BusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    int updateByPrimaryKey(BusUser record);
    /**
     * 验证店长登录名是否存在
     * @param login_name
     * @return
     */
    public int BusUserLogin_name(@Param("login_name")String login_name);
    
    /**
     * 登陆，获取店长信息
     * @param login_name
     * @param password
     * @return
     */
    public BusUser selectUser(@Param("login_name")String login_name,@Param("password")String password);

    /**
     * 查询公众号ID
     * @param userId
     * @return
     */
    public Integer getPbUserId(Integer userId);
    /**
     * 获取商家和管理员所有的菜单
     * @param userId 最初商家id
     * @param level 最初商家等级
     * @param industryid 属性，行业
     * @return
     */
    public List<Map<String,Object>> menusList(@Param("userId")Integer userId,@Param("modelstyle")String modelstyle,@Param("level")Integer level,@Param("industryid")Integer industryid,@Param("loginuc")Integer loginuc);
    /**
     * 获取商家和管理员拥有的菜单版本列表
     * @param userId
     * @param level
     * @param attribute
     * @param loginuc
     * @return
     */
    public List<Map<String,Object>> menusLevelList(@Param("userId")Integer userId,@Param("modelstyle")String modelstyle,@Param("level")Integer level,@Param("industryid")Integer industryid,@Param("loginuc")Integer loginuc);
    /**
     * 店长列表
     * @param shopId
     * @return
     */
    List<Map<String,Object>> listByShop(Integer shopId);

    BusUser getBaseBusByShop(Integer shopId);
    
}