package com.gt.dao.common;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.gt.entity.common.TCommonStaff;

public interface TCommonStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_staff
     *
     * @mbggenerated Wed Nov 16 15:40:34 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_staff
     *
     * @mbggenerated Wed Nov 16 15:40:34 CST 2016
     */
    int insert(TCommonStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_staff
     *
     * @mbggenerated Wed Nov 16 15:40:34 CST 2016
     */
    int insertSelective(TCommonStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_staff
     *
     * @mbggenerated Wed Nov 16 15:40:34 CST 2016
     */
    TCommonStaff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_staff
     *
     * @mbggenerated Wed Nov 16 15:40:34 CST 2016
     */
    int updateByPrimaryKeySelective(TCommonStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_staff
     *
     * @mbggenerated Wed Nov 16 15:40:34 CST 2016
     */
    int updateByPrimaryKey(TCommonStaff record);
    /**
     * 验证员工登录名是否存在
     * @param login_name
     * @return
     */
    public int Stafflogin_name(@Param("login_name")String login_name);
    /**
     * 根据员工的登录名（电话）和密码获取
     * @param login_name
     * @param password
     * @return
     */
    public TCommonStaff selectStaff(@Param("login_name")String login_name,@Param("password")String password);
    /**
     * 管理员或店长，根据登录人信息，在根据登陆二级菜单，获取相对应的子菜单列表
     * @param url
     * @param bus_user_id 最初商家的用户id
     * @param level 最初商家的
     * @return
     */
    public List<Map<String,Object>> zimenusListshop(@Param("url")String url,@Param("bus_user_id")Integer bus_user_id,@Param("level")Integer level);
    /**
     * 员工，根据登录人信息，在根据登陆二级菜单，获取相对应的子菜单列表
     * @param url
     * @param staff_id
     * @return
     */
    public List<Map<String,Object>> menusListStaff(@Param("url")String url,@Param("staff_id")Integer staff_id);
    
    /**
     * 获取主菜单列表
     * @param bus_user_id 最初商家的用户id
     * @param level 最初商家的
     * @param industryid EPR菜单行业属性
     * @return
     */
    public List<Map<String,Object>> menusListshopOne(@Param("bus_user_id")Integer bus_user_id,@Param("level")Integer level,@Param("industryid")Integer industryid);
    /**
     * 获取员工的主菜单列表
     * @param staff_id 员工id
     * @param industryid行业
     * @return
     */
    public List<Map<String,Object>> menusListStaffOne(@Param("staff_id")Integer staff_id,@Param("industryid")Integer industryid);
    /**
     * 根据主菜单获取子菜单列表中最初的菜单url老板店长之类的
     * @param bus_user_id
     * @param level
     * @param pid
     * @return
     */
    public List<Map<String,Object>> menusordershop(@Param("bus_user_id")Integer bus_user_id,@Param("level")Integer level,@Param("pid")Integer pid);
    /**
     * 根据主菜单获取子菜单列表中最初的菜单url员工
     * @param staff_id 员工id
     * @param industryid行业
     * @return
     */
    public List<Map<String,Object>> menusorderstaff(@Param("staff_id")Integer staff_id,@Param("pid")Integer pid);
    
    /**
     * 获取店铺下所有的员工
     * @param resId
     * @return
     */
    public List<TCommonStaff> getAllStaffByResId(@Param("shopId")Integer shopId);
    /**
     * 获取所有的管理员信息
     * @param shopid
     * @return
     */
    List<Map<String,Object>> shopAdminList(Integer shopId);
    /**
     * 根据员工登录人信息，获取所有的菜单
     * @param staff_id 员工id
     * @param industryid 属性
     * @return
     */
    public List<Map<String,Object>> menusList(@Param("staff_id")Integer staff_id,@Param("modelstyle")String industryid,@Param("loginuc")Integer loginuc);
    /**
     * 根据属性获取商家的版本
     * @param staff_id
     * @param industryid
     * @param loginuc
     * @return
     */
    public List<Map<String,Object>> menusLevelList(@Param("staff_id")Integer staff_id,@Param("modelstyle")String industryid,@Param("loginuc")Integer loginuc);

}