package com.gt.entity.common;

import java.util.Date;

public class BusErpLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.id
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_person
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_style
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private Integer logStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_controller
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logController;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_method
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_desc
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_function
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_ip
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_time
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_erp_log.log_type_erp
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    private String logTypeErp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.id
     *
     * @return the value of bus_erp_log.id
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.id
     *
     * @param id the value for bus_erp_log.id
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_person
     *
     * @return the value of bus_erp_log.log_person
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogPerson() {
        return logPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_person
     *
     * @param logPerson the value for bus_erp_log.log_person
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogPerson(String logPerson) {
        this.logPerson = logPerson == null ? null : logPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_style
     *
     * @return the value of bus_erp_log.log_style
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public Integer getLogStyle() {
        return logStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_style
     *
     * @param logStyle the value for bus_erp_log.log_style
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogStyle(Integer logStyle) {
        this.logStyle = logStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_controller
     *
     * @return the value of bus_erp_log.log_controller
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogController() {
        return logController;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_controller
     *
     * @param logController the value for bus_erp_log.log_controller
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogController(String logController) {
        this.logController = logController == null ? null : logController.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_method
     *
     * @return the value of bus_erp_log.log_method
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogMethod() {
        return logMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_method
     *
     * @param logMethod the value for bus_erp_log.log_method
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogMethod(String logMethod) {
        this.logMethod = logMethod == null ? null : logMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_desc
     *
     * @return the value of bus_erp_log.log_desc
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogDesc() {
        return logDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_desc
     *
     * @param logDesc the value for bus_erp_log.log_desc
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogDesc(String logDesc) {
        this.logDesc = logDesc == null ? null : logDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_function
     *
     * @return the value of bus_erp_log.log_function
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogFunction() {
        return logFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_function
     *
     * @param logFunction the value for bus_erp_log.log_function
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogFunction(String logFunction) {
        this.logFunction = logFunction == null ? null : logFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_ip
     *
     * @return the value of bus_erp_log.log_ip
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_ip
     *
     * @param logIp the value for bus_erp_log.log_ip
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp == null ? null : logIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_time
     *
     * @return the value of bus_erp_log.log_time
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_time
     *
     * @param logTime the value for bus_erp_log.log_time
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_erp_log.log_type_erp
     *
     * @return the value of bus_erp_log.log_type_erp
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public String getLogTypeErp() {
        return logTypeErp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_erp_log.log_type_erp
     *
     * @param logTypeErp the value for bus_erp_log.log_type_erp
     *
     * @mbggenerated Fri Dec 23 15:25:17 CST 2016
     */
    public void setLogTypeErp(String logTypeErp) {
        this.logTypeErp = logTypeErp == null ? null : logTypeErp.trim();
    }
}