package com.gt.entity.common;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BusUser implements Serializable {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.name
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.email
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.password
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.phone
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.gender
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.register_ip
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.recent_ip
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String recentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.ctime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.mtime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.status
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.fans_currency
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private BigDecimal fansCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.flow
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Float flow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.city_id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.level
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.startTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.endTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.years
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.statTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Date stattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.industryid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer industryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.pid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.sms_count
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer smsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.istechnique
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer istechnique;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.advert
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer advert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.busmoney_level
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String busmoneyLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.regionids
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String regionids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.isagent
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer isagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.agentid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.realname
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.login_source
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Integer loginSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.is_binding
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Boolean isBinding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.unbundling_time
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private Date unbundlingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.fixed_phone
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String fixedPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.customer_id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    private String customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.id
     *
     * @return the value of bus_user.id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.id
     *
     * @param id the value for bus_user.id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.name
     *
     * @return the value of bus_user.name
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.name
     *
     * @param name the value for bus_user.name
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.email
     *
     * @return the value of bus_user.email
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.email
     *
     * @param email the value for bus_user.email
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.password
     *
     * @return the value of bus_user.password
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.password
     *
     * @param password the value for bus_user.password
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.phone
     *
     * @return the value of bus_user.phone
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.phone
     *
     * @param phone the value for bus_user.phone
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.gender
     *
     * @return the value of bus_user.gender
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.gender
     *
     * @param gender the value for bus_user.gender
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.register_ip
     *
     * @return the value of bus_user.register_ip
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.register_ip
     *
     * @param registerIp the value for bus_user.register_ip
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.recent_ip
     *
     * @return the value of bus_user.recent_ip
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getRecentIp() {
        return recentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.recent_ip
     *
     * @param recentIp the value for bus_user.recent_ip
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setRecentIp(String recentIp) {
        this.recentIp = recentIp == null ? null : recentIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.ctime
     *
     * @return the value of bus_user.ctime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.ctime
     *
     * @param ctime the value for bus_user.ctime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.mtime
     *
     * @return the value of bus_user.mtime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.mtime
     *
     * @param mtime the value for bus_user.mtime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.status
     *
     * @return the value of bus_user.status
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.status
     *
     * @param status the value for bus_user.status
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.fans_currency
     *
     * @return the value of bus_user.fans_currency
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public BigDecimal getFansCurrency() {
        return fansCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.fans_currency
     *
     * @param fansCurrency the value for bus_user.fans_currency
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setFansCurrency(BigDecimal fansCurrency) {
        this.fansCurrency = fansCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.flow
     *
     * @return the value of bus_user.flow
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Float getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.flow
     *
     * @param flow the value for bus_user.flow
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setFlow(Float flow) {
        this.flow = flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.city_id
     *
     * @return the value of bus_user.city_id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.city_id
     *
     * @param cityId the value for bus_user.city_id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.level
     *
     * @return the value of bus_user.level
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.level
     *
     * @param level the value for bus_user.level
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.startTime
     *
     * @return the value of bus_user.startTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.startTime
     *
     * @param starttime the value for bus_user.startTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.endTime
     *
     * @return the value of bus_user.endTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.endTime
     *
     * @param endtime the value for bus_user.endTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.years
     *
     * @return the value of bus_user.years
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.years
     *
     * @param years the value for bus_user.years
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.statTime
     *
     * @return the value of bus_user.statTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Date getStattime() {
        return stattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.statTime
     *
     * @param stattime the value for bus_user.statTime
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setStattime(Date stattime) {
        this.stattime = stattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.industryid
     *
     * @return the value of bus_user.industryid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getIndustryid() {
        return industryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.industryid
     *
     * @param industryid the value for bus_user.industryid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setIndustryid(Integer industryid) {
        this.industryid = industryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.pid
     *
     * @return the value of bus_user.pid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.pid
     *
     * @param pid the value for bus_user.pid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.sms_count
     *
     * @return the value of bus_user.sms_count
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getSmsCount() {
        return smsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.sms_count
     *
     * @param smsCount the value for bus_user.sms_count
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setSmsCount(Integer smsCount) {
        this.smsCount = smsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.istechnique
     *
     * @return the value of bus_user.istechnique
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getIstechnique() {
        return istechnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.istechnique
     *
     * @param istechnique the value for bus_user.istechnique
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setIstechnique(Integer istechnique) {
        this.istechnique = istechnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.advert
     *
     * @return the value of bus_user.advert
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getAdvert() {
        return advert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.advert
     *
     * @param advert the value for bus_user.advert
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setAdvert(Integer advert) {
        this.advert = advert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.busmoney_level
     *
     * @return the value of bus_user.busmoney_level
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getBusmoneyLevel() {
        return busmoneyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.busmoney_level
     *
     * @param busmoneyLevel the value for bus_user.busmoney_level
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setBusmoneyLevel(String busmoneyLevel) {
        this.busmoneyLevel = busmoneyLevel == null ? null : busmoneyLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.regionids
     *
     * @return the value of bus_user.regionids
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getRegionids() {
        return regionids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.regionids
     *
     * @param regionids the value for bus_user.regionids
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setRegionids(String regionids) {
        this.regionids = regionids == null ? null : regionids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.isagent
     *
     * @return the value of bus_user.isagent
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getIsagent() {
        return isagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.isagent
     *
     * @param isagent the value for bus_user.isagent
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setIsagent(Integer isagent) {
        this.isagent = isagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.agentid
     *
     * @return the value of bus_user.agentid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.agentid
     *
     * @param agentid the value for bus_user.agentid
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setAgentid(Integer agentid) {
        this.agentid = agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.realname
     *
     * @return the value of bus_user.realname
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.realname
     *
     * @param realname the value for bus_user.realname
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.login_source
     *
     * @return the value of bus_user.login_source
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Integer getLoginSource() {
        return loginSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.login_source
     *
     * @param loginSource the value for bus_user.login_source
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setLoginSource(Integer loginSource) {
        this.loginSource = loginSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.is_binding
     *
     * @return the value of bus_user.is_binding
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Boolean getIsBinding() {
        return isBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.is_binding
     *
     * @param isBinding the value for bus_user.is_binding
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setIsBinding(Boolean isBinding) {
        this.isBinding = isBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.unbundling_time
     *
     * @return the value of bus_user.unbundling_time
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public Date getUnbundlingTime() {
        return unbundlingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.unbundling_time
     *
     * @param unbundlingTime the value for bus_user.unbundling_time
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setUnbundlingTime(Date unbundlingTime) {
        this.unbundlingTime = unbundlingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.fixed_phone
     *
     * @return the value of bus_user.fixed_phone
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getFixedPhone() {
        return fixedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.fixed_phone
     *
     * @param fixedPhone the value for bus_user.fixed_phone
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setFixedPhone(String fixedPhone) {
        this.fixedPhone = fixedPhone == null ? null : fixedPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.customer_id
     *
     * @return the value of bus_user.customer_id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.customer_id
     *
     * @param customerId the value for bus_user.customer_id
     *
     * @mbggenerated Wed Nov 16 10:25:52 CST 2016
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }
}