package com.gt.entity.common;

import java.io.Serializable;

public class TCommonStaff implements Serializable  {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.id
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.login_name
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.password
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.phone
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.email
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.job_number
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.gender
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.shop_id
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.status
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.create_time
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.create_person
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.recent_ip
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String recentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.remark
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.name
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.isdelect
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer isdelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.positionid
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common_staff.branid
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    private Integer branid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.id
     *
     * @return the value of t_common_staff.id
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.id
     *
     * @param id the value for t_common_staff.id
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.login_name
     *
     * @return the value of t_common_staff.login_name
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.login_name
     *
     * @param loginName the value for t_common_staff.login_name
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.password
     *
     * @return the value of t_common_staff.password
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.password
     *
     * @param password the value for t_common_staff.password
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.phone
     *
     * @return the value of t_common_staff.phone
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.phone
     *
     * @param phone the value for t_common_staff.phone
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.email
     *
     * @return the value of t_common_staff.email
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.email
     *
     * @param email the value for t_common_staff.email
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.job_number
     *
     * @return the value of t_common_staff.job_number
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.job_number
     *
     * @param jobNumber the value for t_common_staff.job_number
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber == null ? null : jobNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.gender
     *
     * @return the value of t_common_staff.gender
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.gender
     *
     * @param gender the value for t_common_staff.gender
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.shop_id
     *
     * @return the value of t_common_staff.shop_id
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.shop_id
     *
     * @param shopId the value for t_common_staff.shop_id
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.status
     *
     * @return the value of t_common_staff.status
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.status
     *
     * @param status the value for t_common_staff.status
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.create_time
     *
     * @return the value of t_common_staff.create_time
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.create_time
     *
     * @param createTime the value for t_common_staff.create_time
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.create_person
     *
     * @return the value of t_common_staff.create_person
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.create_person
     *
     * @param createPerson the value for t_common_staff.create_person
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.recent_ip
     *
     * @return the value of t_common_staff.recent_ip
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getRecentIp() {
        return recentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.recent_ip
     *
     * @param recentIp the value for t_common_staff.recent_ip
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setRecentIp(String recentIp) {
        this.recentIp = recentIp == null ? null : recentIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.remark
     *
     * @return the value of t_common_staff.remark
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.remark
     *
     * @param remark the value for t_common_staff.remark
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.name
     *
     * @return the value of t_common_staff.name
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.name
     *
     * @param name the value for t_common_staff.name
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.isdelect
     *
     * @return the value of t_common_staff.isdelect
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getIsdelect() {
        return isdelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.isdelect
     *
     * @param isdelect the value for t_common_staff.isdelect
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setIsdelect(Integer isdelect) {
        this.isdelect = isdelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.positionid
     *
     * @return the value of t_common_staff.positionid
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.positionid
     *
     * @param positionid the value for t_common_staff.positionid
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common_staff.branid
     *
     * @return the value of t_common_staff.branid
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public Integer getBranid() {
        return branid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common_staff.branid
     *
     * @param branid the value for t_common_staff.branid
     *
     * @mbggenerated Mon Feb 20 15:08:11 CST 2017
     */
    public void setBranid(Integer branid) {
        this.branid = branid;
    }
}